db.url=jdbc:mysql://bv6dtpgk7dfpjgusrjtc-mysql.services.clever-cloud.com:3306/bv6dtpgk7dfpjgusrjtc?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
db.username=u4ezo6ujbhl2ltqc
db.password=ODL7dkZjMVMENPqKgOoe